site_configs: &site_configs
  navbar_brand_html: >
    <a href="/" class="navbar-brand"><b>App</b> Name</a>
  navbar_html: >
    <li><a href="/topics/new">发帖</a>
  wiki_index_html: >
    <div>Wiki Home page.</div>
  wiki_sidebar_html: >
    <strong>推荐内容</strong>
    <ul>
      <li><a href="/wiki/about">关于我们</a></li>
    </ul>
  footer_html: >
    <p class="copyright">
     &copy; Powered by <a href="http://gethomeland.com">Homeland</a>.
    </p>
  after_topic_html: ""
  before_topic_html: ""
  topic_index_sidebar_html: ""
  site_index_html: "下面列出了相关网站。如果你知道还有不在此列表的，请帮忙补充。"
  custom_head_html: >
    <link rel="dns-prefetch" href="//assets.your-host.com">
  node_ids_hide_in_topics_index: ""
  new_topic_dropdown_node_ids: ""
  ban_words_on_reply: >
    mark
    收藏
    顶
    赞
    up
  tips: >
    提示1
    提示2
  newbie_notices: >
    <p>为提高社区质量，防止新人一来就发帖提问，新用户需要达到下面条件才可发帖：</p>
    <ol style="color:#ad2b2d;">
      <li>注册时间超过一个月；</li>
      <li>回帖数量必须达到 10 帖以上；</li>
    </ol>
    <p>请在新人阶段多浏览，看看其他老用户是如何在社区里面分享与解决问题的。</p>
  reject_newbie_reply_in_the_evening: false
  apns_pem: ""
  blacklist_ips: ""

defaults: &defaults
  <<: *site_configs
  app_name: "<%= ENV['app_name'] || 'App Name' %>"
  modules: "<%= ENV['modules'] || 'all' %>"
  domain: "<%= ENV['domain'] || '127.0.0.1' %>"
  https: <%= ENV['https'] || 'true' %>
  admin_emails: <%= (ENV['admin_emails'] || "") %>
  google_analytics_key: "<%= ENV['google_analytics_key'] %>"
  asset_host: "<%= ENV['asset_host'] %>"
  <% if ENV['rack_attack.limit'] %>
  rack_attack:
    limit: <%= ENV['rack_attack.limit'] || 500 %>
    period: <%= ENV['rack_attack.period'] || 60 %>
  <% end %>
  upload_provider: "<%= ENV['upload_provider'] %>" # can be  upyun/aliyun
  upload_access_id: "<%= ENV['upload_access_id'] %>" # or username
  upload_access_secret: "<%= ENV['upload_access_secret'] %>" # or upyun password
  upload_bucket: "<%= ENV['upload_bucket'] %>"
  upload_url: "<%= ENV['upload_url'] %>"
  upload_aliyun_internal: <%= ENV['upload_aliyun_internal'] || false %>
  upload_aliyun_area: "<%= ENV['upload_aliyun_area'] %>"
  mailer_provider: "<%= ENV['mailer_provider'] || 'smtp' %>"
  mailer_sender: "<%= ENV['mailer_sender'] || 'no-reply@127.0.0.1' %>"
  mailer_options:
    <% if ENV['mailer_provider'] == 'postmark' %>
    api_key: '<%= ENV['mailer_options.api_key'] %>'
    <% else %>
    address: '<%= ENV['mailer_options.address'] %>'
    port: <%= ENV['mailer_options.port'] || 25 %>
    domain: '<%= ENV['mailer_options.domain'] %>'
    user_name: '<%= ENV['mailer_options.user_name'] %>'
    password: '<%= ENV['mailer_options.password'] %>'
    authentication: '<%= ENV['mailer_options.authentication'] || 'plain' %>'
    enable_starttls_auto: <%= ENV['mailer_options.enable_starttls_auto'] || true %>
    <% end %>
  github_token: "<%= ENV['github_token'] %>"
  github_secret: "<%= ENV['github_secret'] %>"

production:
  <<: *defaults
